# GitHub Container Registry Secret
# This secret is used to pull images from GitHub Container Registry
# 
# To create this secret, run:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME \
#   --docker-password=YOUR_GITHUB_PAT \
#   --docker-email=YOUR_EMAIL \
#   --namespace=mlops
#
# Or apply this file after encoding your credentials:
# echo -n 'YOUR_GITHUB_USERNAME:YOUR_GITHUB_PAT' | base64
# Then replace ENCODED_AUTH_STRING below

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: mlops
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG
  # Format: {"auths":{"ghcr.io":{"username":"YOUR_GITHUB_USERNAME","password":"YOUR_GITHUB_PAT","email":"YOUR_EMAIL","auth":"BASE64_OF_USERNAME:PAT"}}}
