apiVersion: v1
kind: Service
metadata:
  name: mnist-service
  namespace: default
  labels:
    app: mnist-classifier
spec:
  type: LoadBalancer
  selector:
    app: mnist-classifier
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
